version: '3'
services:
  editor:
    image: scalafiddle/scalafiddle-editor:latest
    restart: always
    container_name: editor
    volumes:
      - sfdata:/data
      - ./config/editor/logback.xml:/app/config/logback.xml
    ports:
      - "9000:9000"
    environment:
      - JAVA_OPTS=-Xmx1G
      - SCALAFIDDLE_SQL_URL=jdbc:postgresql://postgres/scalafiddle
      - SCALAFIDDLE_SQL_USER=scalafiddle
      - SCALAFIDDLE_SQL_PASSWORD
      - APPLICATION_SECRET
      - SCALAFIDDLE_SQL_CONFIG=postgre
      - SCALAFIDDLE_COMPILER_URL=https://embed.scalafiddle.io
      - SCALAFIDDLE_URL=https://scalafiddle.io      
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - SCALAFIDDLE_AUTH_URL=https://scalafiddle.io/authenticate
      - SCALAFIDDLE_LIBRARIES_URL=https://raw.githubusercontent.com/scalafiddle/scalafiddle-io/master/libraries.json
      - SCALAFIDDLE_METRICS_STATSD_HOSTNAME=metrics
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5000"
      
  router:
    image: scalafiddle/scalafiddle-router:latest
    depends_on:
      - editor
    restart: always
    container_name: router
    volumes:
      - sfdata:/data
      - ./config/router/logback.xml:/app/config/logback.xml
    ports:
      - "8888:8880"
    environment:
      - JAVA_OPTS=-Xmx1G
      - SCALAFIDDLE_LIBRARIES_URL=https://raw.githubusercontent.com/scalafiddle/scalafiddle-io/master/libraries.json
      - SCALAFIDDLE_CACHE_DIR=/data/router/cache
      - SCALAFIDDLE_SOURCE_URL=http://editor:9000/raw/
      - SCALAFIDDLE_EDIT_URL=http://editor:9000/
      - SCALAFIDDLE_METRICS_STATSD_HOSTNAME=metrics
      - SCALAFIDDLE_SECRET
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5000"
      
  compiler-2.12:
    image: scalafiddle/scalafiddle-core-2.12:latest
    depends_on:
      - router
    restart: always
    volumes:
      - sfdata:/data
      - ./config/compiler/logback.xml:/app/config/logback.xml
    environment:
      - JAVA_OPTS=-Xmx3G
      - SCALAFIDDLE_ROUTER_URL=ws://router:8880/compiler
      - COURSIER_CACHE=/data/compiler/coursier
      - SCALAFIDDLE_LIBCACHE=/data/compiler/extlibs
      - SCALAFIDDLE_METRICS_STATSD_HOSTNAME=metrics
      - SCALAFIDDLE_SECRET
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5000"
      
  compiler-2.11:
    image: scalafiddle/scalafiddle-core-2.11:latest
    depends_on:
      - router
    restart: always
    volumes:
      - sfdata:/data
      - ./config/compiler/logback.xml:/app/config/logback.xml
    environment:
      - JAVA_OPTS=-Xmx3G
      - SCALAFIDDLE_ROUTER_URL=ws://router:8880/compiler
      - COURSIER_CACHE=/data/compiler/coursier
      - SCALAFIDDLE_LIBCACHE=/data/compiler/extlibs
      - SCALAFIDDLE_METRICS_STATSD_HOSTNAME=metrics
      - SCALAFIDDLE_SECRET
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:5000"
      
volumes:
  sfdata:
